name: Deploy to IONOS (Manual)

on:
  workflow_dispatch: # Erlaubt den manuellen Start über den "Actions" Tab

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🚀 Sync files to IONOS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.IONOS_SFTP }}
          port: 22
          # Wir listen die Dateien explizit auf, um den .git Ordner zu vermeiden
          source: "index.html,proxy.php,.htaccess,assets/**"
          target: "/private/website/"
          # Verhindert, dass die Ordnerstruktur lokal (z.B. .) mit kopiert wird
          strip_components: 0 
